# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrainingSuite', '0003_auto_20160319_1543'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['-number', 'course']},
        ),
        migrations.AddField(
            model_name='session',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
