# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 19:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrainingSuite', '0004_auto_20160319_1834'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['number', 'course']},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['number', 'session']},
        ),
        migrations.AddField(
            model_name='task',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together=set([('number', 'session')]),
        ),
    ]
