# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrainingSuite', '0005_auto_20160319_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='commited',
            field=models.BooleanField(default=False),
        ),
    ]
