# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 15:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TrainingSuite', '0006_solution_commited'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solution',
            old_name='commited',
            new_name='committed',
        ),
    ]
