# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrainingSuite', '0007_auto_20160320_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='default_solution',
            field=models.TextField(default='def test_me(*args, **kwargs):\n    print("Hello World")\n    return True\n', max_length=1000),
        ),
    ]
