# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 18:02
from __future__ import unicode_literals

import TrainingSuite.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrainingSuite', '0009_solution_committed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='physical_location',
            field=models.FileField(blank=True, null=True, upload_to=TrainingSuite.models.Resource.get_resource_path),
        ),
    ]
