# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 18:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TrainingSuite', '0010_auto_20160321_1802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='filename',
            new_name='name',
        ),
    ]
