# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrainingSuite', '0012_auto_20160322_1548'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['target_line', 'author_trainer', 'created_at']},
        ),
        migrations.AddField(
            model_name='course',
            name='number',
            field=models.IntegerField(blank=True, default='1', max_length=1000, null=True),
        ),
    ]
