# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrainingSuite', '0015_auto_20160326_1453'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ['sessions__number']},
        ),
        migrations.AlterField(
            model_name='task',
            name='content',
            field=models.TextField(max_length=3000),
        ),
    ]
