# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 11:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TrainingSuite', '0016_auto_20160326_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='target',
        ),
        migrations.AddField(
            model_name='comment',
            name='target_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TrainingSuite.Comment'),
        ),
        migrations.AddField(
            model_name='comment',
            name='target_solutiuon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TrainingSuite.Solution'),
        ),
    ]
