# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrainingSuite', '0018_auto_20160327_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='description',
            field=models.CharField(default='', max_length=300),
        ),
    ]
