# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 11:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TrainingSuite', '0021_auto_20160327_1419'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='target_solutiuon',
            new_name='target_solution',
        ),
    ]
