# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrainingSuite', '0023_setting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='physical_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
