# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-11 05:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TrainingSuite', '0024_auto_20160328_1224'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['target_line', 'created_at', 'author_trainer', 'author_student']},
        ),
    ]
