# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-29 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrainingSuite', '0025_auto_20160411_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(blank=True, choices=[('PDF', 'PDF file'), ('DOC', 'Word document'), ('PPT', 'Powerpoint presentation'), ('EBOOK', 'Ebook file'), ('URL', 'Link to resource in Web'), ('ZIP', 'Zipped data')], max_length=5),
        ),
    ]
