# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-26 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrainingSuite', '0026_auto_20160429_1245'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['pk']},
        ),
        migrations.AddField(
            model_name='task',
            name='sessions',
            field=models.ManyToManyField(to='TrainingSuite.Session'),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(default='Home Task', max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='task',
            name='number',
        ),
        migrations.RemoveField(
            model_name='task',
            name='session',
        ),
    ]
