# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-19 06:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TrainingSuite', '0029_auto_20160611_2211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('start_date', 'number')},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
    ]
