# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-20 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrainingSuite', '0031_auto_20160920_1441'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slideshow',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='slideshow',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='slideshow',
            name='sessions',
            field=models.ManyToManyField(blank=True, null=True, related_name='slides', through='TrainingSuite.Slides_to_Sessions', to='TrainingSuite.Session'),
        ),
    ]
