# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-26 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrainingSuite', '0033_solution_favorited'),
    ]

    operations = [
        migrations.AddField(
            model_name='slideshow',
            name='courses',
            field=models.ManyToManyField(to='TrainingSuite.Course'),
        ),
        migrations.AlterField(
            model_name='slideshow',
            name='sessions',
            field=models.ManyToManyField(blank=True, related_name='slides', through='TrainingSuite.Slides_to_Sessions', to='TrainingSuite.Session'),
        ),
    ]
