# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-27 05:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrainingSuite', '0034_auto_20161026_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slideshow',
            name='courses',
            field=models.ManyToManyField(blank=True, to='TrainingSuite.Course'),
        ),
    ]
