# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-28 13:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TrainingSuite', '0035_auto_20161027_0841'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('start_date',)},
        ),
        migrations.RemoveField(
            model_name='course',
            name='number',
        ),
    ]
