# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-31 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrainingSuite', '0036_auto_20161028_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='url',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('session', 'New session is available'), ('resource', 'New resource is available'), ('task', 'Task is assigned/updated'), ('comment', 'New reply on solution'), ('solution', 'New solution submitted'), ('quiz', 'Quiz is updated/assigned'), ('discussion_thread', 'New discussion started'), ('discussion_update', 'New message in discussion'), ('general', 'Notification')], default='general', max_length=30),
        ),
    ]
