# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-11 08:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TrainingSuite', '0037_auto_20161031_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('short_name', models.CharField(max_length=20, unique=True)),
                ('color', models.CharField(default='grey', max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Track_to_Trainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TrainingSuite.Track')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TrainingSuite.Trainer')),
            ],
        ),
        migrations.AddField(
            model_name='track',
            name='trainers',
            field=models.ManyToManyField(related_name='tracks', through='TrainingSuite.Track_to_Trainer', to='TrainingSuite.Trainer'),
        ),
    ]
