# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-11 09:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TrainingSuite', '0038_auto_20161111_1012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_to_Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TrainingSuite.Course')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TrainingSuite.Track')),
            ],
        ),
        migrations.AddField(
            model_name='resource',
            name='track',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TrainingSuite.Track'),
        ),
        migrations.AddField(
            model_name='slideshow',
            name='track',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TrainingSuite.Track'),
        ),
        migrations.AddField(
            model_name='task',
            name='track',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TrainingSuite.Track'),
        ),
        migrations.AddField(
            model_name='course',
            name='tracks',
            field=models.ManyToManyField(related_name='tracks', through='TrainingSuite.Course_to_Track', to='TrainingSuite.Track'),
        ),
    ]
