# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-17 11:56
from __future__ import unicode_literals

import TrainingSuite.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TrainingSuite', '0039_auto_20161111_1147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Runner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('token', models.CharField(blank=True, default='', max_length=200, null=TrainingSuite.models.Track)),
                ('token_name', models.CharField(default='API_TOKEN', max_length=50)),
                ('url', models.CharField(max_length=200)),
                ('query_method', models.CharField(default='post', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Runner_to_Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TrainingSuite.Runner')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TrainingSuite.Track')),
            ],
        ),
        migrations.AddField(
            model_name='runner',
            name='tracks',
            field=models.ManyToManyField(related_name='runners', through='TrainingSuite.Runner_to_Track', to='TrainingSuite.Track'),
        ),
    ]
