# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-17 13:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0018_auto_20161103_1518'),
        ('TrainingSuite', '0039_auto_20161111_1147'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfflineCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(max_length=3000)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TrainingSuite.Trainer')),
            ],
        ),
        migrations.CreateModel(
            name='OfflineCourse_to_Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offline_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TrainingSuite.OfflineCourse')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TrainingSuite.Track')),
            ],
        ),
        migrations.CreateModel(
            name='OfflineSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('description', models.TextField(default='', max_length=3000)),
                ('required', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TrainingSuite.OfflineCourse')),
                ('quiz_next', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offline_sessions_next', to='quiz.Quiz')),
                ('quiz_prev', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offline_sessions_prev', to='quiz.Quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Resource_to_OfflineSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TrainingSuite.Resource')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TrainingSuite.OfflineSession')),
            ],
        ),
        migrations.CreateModel(
            name='Slideshow_to_OfflineSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TrainingSuite.OfflineSession')),
                ('slideshow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TrainingSuite.Slideshow')),
            ],
        ),
        migrations.CreateModel(
            name='Task_to_OfflineSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TrainingSuite.OfflineSession')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TrainingSuite.Task')),
            ],
        ),
        migrations.AddField(
            model_name='offlinesession',
            name='resources',
            field=models.ManyToManyField(related_name='offline_sessions', through='TrainingSuite.Resource_to_OfflineSession', to='TrainingSuite.Resource'),
        ),
        migrations.AddField(
            model_name='offlinesession',
            name='slides',
            field=models.ManyToManyField(related_name='offline_sessions', through='TrainingSuite.Slideshow_to_OfflineSession', to='TrainingSuite.Slideshow'),
        ),
        migrations.AddField(
            model_name='offlinesession',
            name='tasks',
            field=models.ManyToManyField(related_name='offline_sessions', through='TrainingSuite.Task_to_OfflineSession', to='TrainingSuite.Task'),
        ),
        migrations.AddField(
            model_name='offlinecourse',
            name='tracks',
            field=models.ManyToManyField(related_name='offline_courses', through='TrainingSuite.OfflineCourse_to_Track', to='TrainingSuite.Track'),
        ),
        migrations.AddField(
            model_name='student',
            name='offline_courses',
            field=models.ManyToManyField(blank=True, to='TrainingSuite.OfflineCourse'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='offline_courses',
            field=models.ManyToManyField(blank=True, to='TrainingSuite.OfflineCourse'),
        ),
        migrations.AlterUniqueTogether(
            name='offlinesession',
            unique_together=set([('course', 'name')]),
        ),
    ]
