# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-17 12:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TrainingSuite', '0040_auto_20161117_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='runner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='TrainingSuite.Runner'),
            preserve_default=False,
        ),
    ]
