# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-18 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrainingSuite', '0040_auto_20161117_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='offlinecourse',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
