# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-18 12:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TrainingSuite', '0041_offlinecourse_active'),
        ('TrainingSuite', '0041_task_runner'),
    ]

    operations = [
    ]
