# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-18 12:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TrainingSuite', '0042_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfflineCourseResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passed', models.BooleanField(default=False)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('results', models.TextField(blank=True, max_length=1000, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TrainingSuite.OfflineCourse')),
                ('current_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TrainingSuite.OfflineSession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TrainingSuite.Student')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='offlinecourseresults',
            unique_together=set([('student', 'course')]),
        ),
    ]
