# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-18 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrainingSuite', '0043_auto_20161118_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='offlinecourse',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offlinecourse',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
