# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-22 07:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0018_auto_20161103_1518'),
        ('TrainingSuite', '0044_auto_20161118_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offlinesession',
            name='quiz_next',
        ),
        migrations.RemoveField(
            model_name='offlinesession',
            name='quiz_prev',
        ),
        migrations.AddField(
            model_name='offlinesession',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offline_sessions', to='quiz.Quiz'),
        ),
    ]
