# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-22 11:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TrainingSuite', '0045_auto_20161122_0931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='short_description',
            new_name='name',
        ),
    ]
