# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-28 13:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TrainingSuite', '0046_auto_20161122_1331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offlinesession',
            old_name='number',
            new_name='order',
        ),
        migrations.AlterUniqueTogether(
            name='offlinesession',
            unique_together=set([('course', 'name', 'order')]),
        ),
    ]
