# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-29 07:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TrainingSuite', '0047_auto_20161128_1559'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offlinesession',
            options={'ordering': ['-order']},
        ),
    ]
