# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-29 07:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TrainingSuite', '0048_auto_20161129_0945'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offlinesession',
            options={'ordering': ['order']},
        ),
    ]
