# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-01 10:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TrainingSuite', '0049_auto_20161129_0946'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TrainingSuite.Session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TrainingSuite.Student')),
            ],
        ),
    ]
