# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-01 11:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TrainingSuite', '0050_attendance'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set([('session', 'student')]),
        ),
    ]
