# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-01 12:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TrainingSuite', '0051_auto_20161201_1305'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['order', 'course']},
        ),
        migrations.RenameField(
            model_name='session',
            old_name='number',
            new_name='order',
        ),
        migrations.AlterUniqueTogether(
            name='session',
            unique_together=set([('order', 'course')]),
        ),
    ]
