# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-13 10:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TrainingSuite', '0025_auto_20160411_0849'),
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmittedResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('date_submitted', models.DateField()),
            ],
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='correctness',
            new_name='correct',
        ),
        migrations.AddField(
            model_name='quiz',
            name='passing_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submittedresult',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Quiz'),
        ),
        migrations.AddField(
            model_name='submittedresult',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TrainingSuite.Student'),
        ),
    ]
