# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-18 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_question_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
