# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-27 07:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20160426_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='students',
        ),
    ]
