# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-28 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_remove_quiz_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittedresult',
            name='chosen_answers',
            field=models.ManyToManyField(to='quiz.Answer'),
        ),
    ]
