# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-28 13:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_submittedresult_chosen_answers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submittedresult',
            old_name='chosen_answers',
            new_name='answers',
        ),
    ]
