# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-29 06:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_auto_20160428_1655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='weight',
            new_name='score',
        ),
    ]
