# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-12 13:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TrainingSuite', '0025_auto_20160411_0849'),
        ('quiz', '0012_quiz_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizTries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tries', models.IntegerField(default=0)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Quiz')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TrainingSuite.Student')),
            ],
        ),
    ]
