# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-19 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_auto_20160513_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittedresult',
            name='passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submittedresult',
            name='passing_questions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submittedresult',
            name='passing_score',
            field=models.IntegerField(default=0),
        ),
    ]
