# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-19 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0016_submittedresult_passed_by_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submittedresult',
            name='passed_by_score',
        ),
        migrations.RemoveField(
            model_name='submittedresult',
            name='passing_questions',
        ),
        migrations.RemoveField(
            model_name='submittedresult',
            name='passing_score',
        ),
        migrations.AddField(
            model_name='quiz',
            name='passed_by_score',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quiz',
            name='passing_questions',
            field=models.IntegerField(default=0),
        ),
    ]
