# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-03 13:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0017_auto_20160519_1357'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='submittedresult',
            unique_together=set([('student', 'quiz')]),
        ),
    ]
