# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-22 13:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TrainingSuite', '0046_auto_20161122_1331'),
        ('quiz', '0018_auto_20161103_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz_to_Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Quiz')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TrainingSuite.Track')),
            ],
        ),
        migrations.AddField(
            model_name='quiz',
            name='tracks',
            field=models.ManyToManyField(blank=True, related_name='quizes', through='quiz.Quiz_to_Track', to='TrainingSuite.Track'),
        ),
    ]
