# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-28 14:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('form_type', models.CharField(choices=[('text', 'CharField'), ('multiple entries', 'ChoiceField'), ('digit', 'IntegerField'), ('boolean', 'BooleanField'), ('date', 'DateField'), ('e-mail', 'EmailField'), ('file', 'FileField'), ('image', 'ImageField'), ('URL', 'URLField')], default='CharField', max_length=20)),
                ('widget_type', models.CharField(default='TextInput', max_length=20)),
                ('choices', models.CharField(default='', max_length=1000)),
                ('help_message', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('form_type', models.CharField(choices=[('text', 'CharField'), ('multiple entries', 'ChoiceField'), ('digit', 'IntegerField'), ('boolean', 'BooleanField'), ('date', 'DateField'), ('e-mail', 'EmailField'), ('file', 'FileField'), ('image', 'ImageField'), ('URL', 'URLField')], default='CharField', max_length=20)),
                ('widget_type', models.CharField(default='TextInput', max_length=20)),
                ('choices', models.CharField(default='', max_length=1000)),
                ('help_message', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
