# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-28 15:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersetting',
            name='user',
        ),
    ]
