# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-17 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_remove_usersetting_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=40)),
                ('nickname', models.CharField(max_length=15, unique=True)),
                ('phone', models.IntegerField(max_length=18)),
                ('photo', models.FileField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='globalsetting',
            name='choices',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='globalsetting',
            name='form_type',
            field=models.CharField(choices=[('CharField', 'Text'), ('ChoiceField', 'Selection'), ('IntegerField', 'Digit'), ('BooleanField', 'Boolean'), ('DateField', 'Date'), ('EmailField', 'E-mail'), ('FileField', 'File upload'), ('ImageField', 'Image'), ('URLField', 'URL')], default='CharField', max_length=20),
        ),
        migrations.AlterField(
            model_name='globalsetting',
            name='help_message',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='globalsetting',
            name='widget_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='choices',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='form_type',
            field=models.CharField(choices=[('CharField', 'Text'), ('ChoiceField', 'Selection'), ('IntegerField', 'Digit'), ('BooleanField', 'Boolean'), ('DateField', 'Date'), ('EmailField', 'E-mail'), ('FileField', 'File upload'), ('ImageField', 'Image'), ('URLField', 'URL')], default='CharField', max_length=20),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='help_message',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='widget_type',
            field=models.CharField(max_length=20),
        ),
    ]
