# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-18 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_auto_20161017_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.CharField(max_length=256),
        ),
    ]
