# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-25 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20160525_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='has_multiple_options',
            field=models.BooleanField(default=False),
        ),
    ]
