# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-25 08:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_question_has_multiple_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittedresult',
            name='custom_options',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.UserOption'),
        ),
        migrations.AddField(
            model_name='submittedresult',
            name='options',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Option'),
        ),
    ]
