# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-26 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_poll_verbose_results_enabled'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='option',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['pk']},
        ),
        migrations.RemoveField(
            model_name='submittedresult',
            name='custom_options',
        ),
        migrations.AddField(
            model_name='submittedresult',
            name='user_options',
            field=models.ManyToManyField(blank=True, to='polls.UserOption'),
        ),
        migrations.AlterField(
            model_name='submittedresult',
            name='options',
            field=models.ManyToManyField(blank=True, to='polls.Option'),
        ),
    ]
