# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-03 06:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussionthread',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TrainingSuite.Course'),
        ),
        migrations.AlterField(
            model_name='discussionthread',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TrainingSuite.Session'),
        ),
    ]
