# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-07 07:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0002_auto_20160603_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussionmessage',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='discussions.DiscussionMessage'),
        ),
    ]
