# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-06 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0003_auto_20160607_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussionthread',
            name='content',
            field=models.TextField(default='Help me understand please!', max_length=5000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='discussionmessage',
            name='content',
            field=models.TextField(max_length=5000),
        ),
    ]
