# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-06 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0004_auto_20160706_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussionthread',
            name='content',
            field=models.TextField(default='', max_length=5000),
        ),
    ]
