# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-07 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0005_auto_20160706_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussionmessage',
            name='target',
        ),
        migrations.AddField(
            model_name='discussionmessage',
            name='quote',
            field=models.TextField(default='', max_length=5000),
        ),
    ]
